name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' # Use the correct version of .NET for your project

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore HealthyPawsV2/HealthyPawsV2.csproj

      # Build the project
      - name: Build project
        run: dotnet publish HealthyPawsV2/HealthyPawsV2.csproj -c Release -o publish

      # Deploy to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_RIVER_090E12610 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "HealthyPawsV2/wwwroot" # Path to static files (e.g., Razor Pages)
          api_location: "api" # Adjust if you have an API folder; otherwise, leave blank or remove
          output_location: "publish" # Path to published files

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_RIVER_090E12610 }}
          action: "close"
