name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Install .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0' # Change to your .NET version

      # Restore dependencies using the solution file
      - name: Restore dependencies
        run: dotnet restore HealthyPawsV2.sln

      # Build the application using the solution file
      - name: Build the app
        run: dotnet build HealthyPawsV2.sln --configuration Release

      # Publish the application to output directory
      - name: Publish the app
        run: dotnet publish HealthyPawsV2.sln --configuration Release --output ${{ github.workspace }}/publish

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_RIVER_090E12610 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "HealthyPawsV2/HealthyPawsV2" # Correct path to app source code
          api_location: "api" # Api source code path - optional
          output_location: "publish" # This should match the folder where you published your app

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_RIVER_090E12610 }}
          action: "close"
